### ISSUE TITLE
What about `required` constraint, `nil` and empty string?

### ISSUE THREAD

**Issue by mt0erfztxt** [friemen/examine#3]
The docs says:
> **required**
> Constraint-fn that passes if value is not nil.

Today I came across the fact that actually it fails not only when value is `nil` but also when it's an empty string, for example:
```clojure
(require '[examine.core :as e])
(require '[examine.constraints :as c])

(def rule-set
  (e/rule-set :my-field c/required c/not-nil? c/is-string (c/min-length 4)))

;; Case when validated data doesn't contain specified path works as expected.
(e/messages (e/validate rule-set {}))
;; => {:my-field ("A value is required")}

;; Case when validated data contain specified path with value set to
;; `nil` also works as expected.
(e/messages (e/validate rule-set {:my-field nil}))
;; => {:my-field ("A value is required")}

;; Case when validated data contain specified path with value set to empty
;; string works not as expected - according to docs "A value is required"
;; message must not be present in list of messages.
(e/messages (e/validate rule-set {:my-field ""}))
;; => {:my-field ("Min 4 characters required" "A value is required")}
```
I think that behaviour of `required` constraint that stated in docs is correct one and so I skimmed through the [code](https://github.com/friemen/examine/blob/994f823d84344fe65ce44c035fe36e851c983db2/src/examine/constraints.cljc#L64) of `required` constraint and found that it uses `not-blank?` predicate and that's why we have what we have :) But what you think about that?

P.S. I can patch `required` constraint or docs and make a PR if needed.

**Comment by friemen** [comment]
Thanks for the observation and the offer to help.
Actually, the current state of the code (nil or blank violates the required constraint) is what I intended and the doc is incomplete.
The library is meant be used to validate user input. In textfields, a user would consider the empty string the same as "input is missing". From a user perspective, nil is the same: "input is missing".

I'll fix the docucmentation.

**Comment by mt0erfztxt** [comment]
Thanks for clarification.
I understand intentions of your decision - sometimes we need to choose between semantically right ```(is (not= nil ""))``` and logically right for our use case ```(is (and (empty? nil) (empty? "")))```.
